export const languageOptions = [
    { value:'Abkhazian', label:'Abkhazian' },
  { value:'Afar', label:'Afar' },
  { value:'Afrikaans', label:'Afrikaans' },
  { value:'Albanian', label:'Albanian' },
  { value:'Amharic', label:'Amharic' },
  { value:'Arabic', label:'Arabic' },
  { value:'Aragonese', label:'Aragonese' },
  { value:'Armenian', label:'Armenian' },
  { value:'Assamese', label:'Assamese' },
  { value:'Aymara', label:'Aymara' },
  { value:'Azerbaijani', label:'Azerbaijani' },
  { value:'Bashkir', label:'Bashkir' },
  { value:'Basque', label:'Basque' },
  { value:'Bengali (Bangla', label:'Bengali (Bangla' },
  { value:'Bhutani', label:'Bhutani' },
  { value:'Bihari', label:'Bihari' },
  { value:'Bislama', label:'Bislama' },
  { value:'Breton', label:'Breton' },
  { value:'Bulgarian', label:'Bulgarian' },
  { value:'Burmese', label:'Burmese' },
  { value:'Byelorussian (Belarusian', label:'Byelorussian (Belarusian' },
  { value:'Cambodian', label:'Cambodian' },
  { value:'Catalan', label:'Catalan' },
  { value:'Cherokee', label:'Cherokee' },
  { value:'Chinese', label:'Chinese' },
  { value:'Chinese (Simplified)  zh', label:'Chinese (Simplified) zh' },
  { value:'Chinese (Traditional) zh', label:'Chinese (Traditional)  zh' },
  { value:'Corsican', label:'Corsican' },
  { value:'Croatian', label:'Croatian' },
  { value:'Czech', label:'Czech' },
  { value:'Danish', label:'Danish' },
  { value:'Dutch', label:'Dutch' },
  { value:'English', label:'English' },
  { value:'Esperanto', label:'Esperanto' },
  { value:'Estonian', label:'Estonian' },
  { value:'Faeroese', label:'Faeroese' },
  { value:'Farsi', label:'Farsi' },
  { value:'Fiji', label:'Fiji' },
  { value:'Finnish', label:'Finnish' },
  { value:'French', label:'French' },
  { value:'Frisian', label:'Frisian' },
  { value:'Galician', label:'Galician' },
  { value:'Gaelic (Scottish', label:'Gaelic (Scottish' },
  { value:'Gaelic (Manx', label:'Gaelic (Manx' },
  { value:'Georgian', label:'Georgian' },
  { value:'German', label:'German' },
  { value:'Greek', label:'Greek' },
  { value:'Greenlandic', label:'Greenlandic' },
  { value:'Guarani', label:'Guarani' },
  { value:'Gujarati', label:'Gujarati' },
  { value:'Haitian Creole', label:'Haitian Creole' },
  { value:'Hausa', label:'Hausa' },
  { value:'Hawaiian', label:'Hawaiian' },
  { value:'Hebrew  he', label:'Hebrew he' },
  { value:'Hindi', label:'Hindi' },
  { value:'Hungarian', label:'Hungarian' },
  { value:'Icelandic', label:'Icelandic' },
  { value:'Ido', label:'Ido' },
  { value:'Indonesian  id', label:'Indonesian id' },
  { value:'Interlingua', label:'Interlingua' },
  { value:'Interlingue', label:'Interlingue' },
  { value:'Inuktitut', label:'Inuktitut' },
  { value:'Inupiak', label:'Inupiak' },
  { value:'Irish', label:'Irish' },
  { value:'Italian', label:'Italian' },
  { value:'Japanese', label:'Japanese' },
  { value:'Javanese', label:'Javanese' },
  { value:'Kannada', label:'Kannada' },
  { value:'Kashmiri', label:'Kashmiri' },
  { value:'Kazakh', label:'Kazakh' },
  { value:'Kinyarwanda (Ruanda', label:'Kinyarwanda (Ruanda' },
  { value:'Kirghiz', label:'Kirghiz' },
  { value:'Kirundi (Rundi', label:'Kirundi (Rundi' },
  { value:'Korean', label:'Korean' },
  { value:'Kurdish', label:'Kurdish' },
  { value:'Laothian', label:'Laothian' },
  { value:'Latin', label:'Latin' },
  { value:'Latvian (Lettish', label:'Latvian (Lettish' },
  { value:'Limburgish ( Limburger', label:'Limburgish ( Limburger' },
  { value:'Lingala', label:'Lingala' },
  { value:'Lithuanian', label:'Lithuanian' },
  { value:'Macedonian', label:'Macedonian' },
  { value:'Malagasy', label:'Malagasy' },
  { value:'Malay', label:'Malay' },
  { value:'Malayalam', label:'Malayalam' },
  { value:'Maltese', label:'Maltese' },
  { value:'Maori', label:'Maori' },
  { value:'Marathi', label:'Marathi' },
  { value:'Moldavian', label:'Moldavian' },
  { value:'Mongolian', label:'Mongolian' },
  { value:'Nauru', label:'Nauru' },
  { value:'Nepali', label:'Nepali' },
  { value: 'None', label: 'None' },
  { value:'Norwegian', label:'Norwegian' },
  { value:'Occitan', label:'Occitan' },
  { value:'Oriya', label:'Oriya' },
  { value:'Oromo (Afaan Oromo', label:'Oromo (Afaan Oromo' },
  { value:'Pashto (Pushto', label:'Pashto (Pushto' },
  { value:'Polish', label:'Polish' },
  { value:'Portuguese', label:'Portuguese' },
  { value:'Punjabi', label:'Punjabi' },
  { value:'Quechua', label:'Quechua' },
  { value:'Rhaeto-Romance', label:'Rhaeto-Romance' },
  { value:'Romanian', label:'Romanian' },
  { value:'Russian', label:'Russian' },
  { value:'Sami', label:'Sami' },
  { value:'Sangro', label:'Sangro' },
  { value:'Sanskrit', label:'Sanskrit' },
  { value:'Serbian', label:'Serbian' },
  { value:'Serbo-Croatian', label:'Serbo-Croatian' },
  { value:'Sesotho', label:'Sesotho' },
  { value:'Setswana', label:'Setswana' },
  { value:'Shona', label:'Shona' },
  { value:'Sichuan Yi', label:'Sichuan Yi' },
  { value:'Sindhi', label:'Sindhi' },
  { value:'Sinhalese', label:'Sinhalese' },
  { value:'Siswati', label:'Siswati' },
  { value:'Slovak', label:'Slovak' },
  { value:'Slovenian', label:'Slovenian' },
  { value:'Somali', label:'Somali' },
  { value:'Spanish', label:'Spanish' },
  { value:'Sundanese', label:'Sundanese' },
  { value:'Swahili (Kiswahili', label:'Swahili (Kiswahili' },
  { value:'Swedish', label:'Swedish' },
  { value:'Tagalog', label:'Tagalog' },
  { value:'Tajik', label:'Tajik' },
  { value:'Tamil', label:'Tamil' },
  { value:'Tatar', label:'Tatar' },
  { value:'Telugu', label:'Telugu' },
  { value:'Thai', label:'Thai' },
  { value:'Tibetan', label:'Tibetan' },
  { value:'Tigrinya', label:'Tigrinya' },
  { value:'Tonga', label:'Tonga' },
  { value:'Tsonga', label:'Tsonga' },
  { value:'Turkish', label:'Turkish' },
  { value:'Turkmen', label:'Turkmen' },
  { value:'Twi', label:'Twi' },
  { value:'Uighur', label:'Uighur' },
  { value:'Ukrainian', label:'Ukrainian' },
  { value:'Urdu', label:'Urdu' },
  { value:'Uzbek', label:'Uzbek' },
  { value:'Vietnamese', label:'Vietnamese' },
  { value:'Volapük', label:'Volapük' },
  { value:'Wallon', label:'Wallon' },
  { value:'Welsh', label:'Welsh' },
  { value:'Wolof', label:'Wolof' },
  { value:'Xhosa', label:'Xhosa' },
  { value:'Yiddish yi', label:'Yiddish  yi' },
  { value:'Yoruba', label:'Yoruba' },
  { value:'Zulu', label:'Zulu' }
]
