export const graduateOptions = [
  { value:'Applied Math', label:'Applied Math' },
  { value:'Applied Physics', label:'Applied Physics' },
  { value:'Applied Statistics', label:'Applied Statistics' },
  { value:'Architecture', label:'Architecture' },
  { value:'Bioelectronics', label:'Bioelectronics' },
  { value:'Bioinformatics', label:'Bioinformatics' },
  { value:'Biology', label:'Biology' },
  { value:'Biomedical Engineering', label:'Biomedical Engineering' },
  { value:'Biopharmaceutical Engineering', label:'Biopharmaceutical Engineering' },
  { value:'Biostatistics', label:'Biostatistics' },
  { value:'Business Administration in Management', label:'Business Administration in Management' },
  { value:'Business and Information Systems', label:'Business and Information Systems' },
  { value:'Chemical Engineering', label:'Chemical Engineering' },
  { value:'Chemistry', label:'Chemistry' },
  { value:'Civil Engineering', label:'Civil Engineering' },
  { value:'Collaborative Doctorate', label:'Collaborative Doctorate' },
  { value:'Computational Biology', label:'Computational Biology' },
  { value:'Computer Engineering', label:'Computer Engineering' },
  { value:'Computer Science', label:'Computer Science' },
  { value:'Computing and Business', label:'Computing and Business' },
  { value:'Critical Infrastructure Systems', label:'Critical Infrastructure Systems' },
  { value:'Cyber Security and Privacy', label:'Cyber Security and Privacy' },
  { value:'Electrical Engineering', label:'Electrical Engineering' },
  { value:'Emergency Management and Business', label:'Emergency Management and Business' },
  { value:'Engineering Management', label:'Engineering Management' },
  { value:'Engineering Science', label:'Engineering Science' },
  { value:'Environmental Engineering', label:'Environmental Engineering' },
  { value:'Environmental and Sustainability Policy', label:'Environmental and Sustainability Policy' },
  { value:'Environmental Science', label:'Environmental Science' },
  { value:'Finance', label:'Finance' },
  { value:'Healthcare Systems Management', label:'Healthcare Systems Management' },
  { value:'History', label:'History' },
  { value:'Industrial Engineering', label:'Industrial Engineering' },
  { value:'Information Systems', label:'Information Systems' },
  { value:'Infrastructure Planning', label:'Infrastructure Planning' },
  { value:'International Business', label:'International Business' },
  { value:'Internet Engineering', label:'Internet Engineering' },
  { value:'Information Technology and Management', label:'Information Technology and Management' },
  { value:'Management of Information Systems', label:'Management of Information Systems' },
  { value:'Management of Technology (EMBA)', label:'Management of Technology (EMBA)' },
  { value:'Management of Technology (MBA)', label:'Management of Technology (MBA)' },
  { value:'Manufacturing Systems Engineering', label:'Manufacturing Systems Engineering' },
  { value:'Materials Science and Engineering', label:'Materials Science and Engineering' },
  { value:'Mathematical and Computational Finance', label:'Mathematical and Computational Finance' },
  { value:'Mathematical Sciences', label:'Mathematical Sciences' },
  { value:'Mechanical Engineering', label:'Mechanical Engineering' },
  { value:'Occupational Safety and Health', label:'Occupational Safety and Health' },
  { value:'Pharmaceutical Chemistry', label:'Pharmaceutical Chemistry' },
  { value:'Pharmaceutical Engineering', label:'Pharmaceutical Engineering' },
  { value:'Pharmaceutical Systems Management', label:'Pharmaceutical Systems Management' },
  { value:'Physics', label:'Physics' },
  { value:'Power and Energy Systems', label:'Power and Energy Systems' },
  { value:'Software Engineering', label:'Software Engineering' },
  { value:'Telecommunications', label:'Telecommunications' },
  { value:'Transportation', label:'Transportation' },
  { value:'Urban Systems', label:'Urban Systems' }
]
export const undergraduateOptions = [
  { value:'Architecture', label:'Architecture' },
  { value:'Biochemistry', label:'Biochemistry' },
  { value:'Bioinformatics', label:'Bioinformatics' },
  { value:'Biology', label:'Biology' },
  { value:'Biomedical Engineering', label:'Biomedical Engineering' },
  { value:'Biomechanics', label:'Biomechanics' },
  { value:'Bioinstrumentation', label:'Bioinstrumentation' },
  { value:'Biomaterials and Tissue Engineering', label:'Biomaterials and Tissue Engineering' },
  { value:'Biophysics', label:'Biophysics' },
  { value:'Business', label:'Business' },
  { value:'Accounting', label:'Accounting' },
  { value:'Finance', label:'Finance' },
  { value:'Innovation and Entrepreneurship', label:'Innovation and Entrepreneurship' },
  { value:'International Business', label:'International Business' },
  { value:'Management Information Systems', label:'Management Information Systems' },
  { value:'Marketing', label:'Marketing' },
  { value:'Business and Information Systems', label:'Business and Information Systems' },
  { value:'Chemical Engineering', label:'Chemical Engineering' },
  { value:'Chemistry', label:'Chemistry' },
  { value:'Civil Engineering', label:'Civil Engineering' },
  { value:'Communication and Media', label:'Communication and Media' },
  { value:'Computer Engineering', label:'Computer Engineering' },
  { value:'Computer Science', label:'Computer Science' },
  { value:'Computing and Business', label:'Computing and Business' },
  { value:'Engineering Science', label:'Engineering Science' },
  { value:'Engineering Technology', label:'Engineering Technology' },
  { value:'Computer Technology (CPT/CMPT)', label:'Computer Technology (CPT/CMPT)' },
  { value:'Concrete Industry Management (CIMT)', label:'Concrete Industry Management (CIMT)' },
  { value:'Digital Design', label:'Digital Design' },
  { value:'Electrical Engineering', label:'Electrical Engineering' },
  { value:'Engineering Science', label:'Engineering Science' },
  { value:'Mechanical Engineering Technology', label:'Mechanical Engineering Technology' },
  { value:'Medical Informatics Technology (MIT)', label:'Medical Informatics Technology (MIT)' },
  { value:'Surveying Engineering Technology', label:'Surveying Engineering Technology' },
  { value:'Technology Education (TEED)', label:'Technology Education (TEED)' },
  { value:'Telecommunications Management', label:'Telecommunications Management' },
  { value:'Environmental Sciences', label:'Environmental Sciences' },
  { value:'History', label:'History' },
  { value:'Human Computer Interaction', label:'Human Computer Interaction' },
  { value:'Industrial Design', label:'Industrial Design' },
  { value:'Industrial Engineering', label:'Industrial Engineering' },
  { value:'Information Systems', label:'Information Systems' },
  { value:'Information Technology', label:'Information Technology' },
  { value:'Interior Design', label:'Interior Design' },
  { value:'Law, Technology and Culture', label:'Law, Technology and Culture' },
  { value:'Mathematical Sciences', label:'Mathematical Sciences' },
  { value:'Applied Math', label:'Applied Math' },
  { value:'Applied Statistics', label:'Applied Statistics' },
  { value:'Mathematical Biology', label:'Mathematical Biology' },
  { value:'Mathematics of Finance and Actuarial', label:'Mathematics of Finance and Actuarial' },
  { value:'Mechanical Engineering', label:'Mechanical Engineering' },
  { value:'Patent Law, Technology and Culture', label:'Patent Law, Technology and Culture' },
  { value:'Science, Technology and Culture', label:'Science, Technology and Culture' },
  { value:'Theatre, Arts and Technology', label:'Theatre, Arts and Technology' },
  { value:'Web and Information Systems', label:'Web and Information Systems' }
]
