export const organizationsOptions = [
{ value: 'Actuarial Society', label: 'Actuarial Society' },
{ value: 'American Chemical Society', label: 'American Chemical Society' },
{ value: 'Alpha Sigma Phi Fraternity', label: 'Alpha Sigma Phi Fraternity' },
{ value: 'African Student Association', label: 'African Student Association' },
{ value: 'American Institute of Aeronautics and Astronautics', label: 'American Institute of Aeronautics and Astronautics' },
{ value: 'American Water Works Association', label: 'American Water Works Association' },
{ value: 'Alpha Phi Omega (Service Fraternity)', label: 'Alpha Phi Omega (Service Fraternity)' },
{ value: 'Alpha Rho Chi (Architecture Fraternity)', label: 'Alpha Rho Chi (Architecture Fraternity)' },
{ value: 'Alpha Sigma Tau Sorority', label: 'Alpha Sigma Tau Sorority' },
{ value: 'American Concrete Institute', label: 'American Concrete Institute' },
{ value: 'American Institute of Chemical Engineers', label: 'American Institute of Chemical Engineers' },
{ value: 'American Society of Mechanical Engineering', label: 'American Society of Mechanical Engineering' },
{ value: 'Association for Computing Machinery', label: 'Association for Computing Machinery' },
{ value: 'Association of Indian Students', label: 'Association of Indian Students' },
{ value: 'BAPS Christian Fellowship', label: 'BAPS Christian Fellowship' },
{ value: "Bangladeshi Students' Association", label: "Bangladeshi Students' Association" },
{ value: 'Beta Beta Beta (Biological Honor Society)', label: 'Beta Beta Beta (Biological Honor Society)' },
{ value: 'Bible Study Club', label: 'Bible Study Club' },
{ value: 'Brick City Ehaas', label: 'Brick City Ehaas' },
{ value: 'Business Club', label: 'Business Club' },
{ value: 'Biology Society', label: 'Biology Society' },
{ value: 'BioMedical Engineering Society', label: 'BioMedical Engineering Society' },
{ value: 'Christians on Campus', label: 'Christians on Campus' },
{ value: 'Community Connection', label: 'Community Connection' },
{ value: 'College Panhellenic CouncilPanhellenic Council', label: 'College Panhellenic CouncilPanhellenic Council' },
{ value: 'Chinese Student and Scholar Association ', label: 'Chinese Student and Scholar Association ' },
{ value: 'Campus Cruisade for Christ at NJIT', label: 'Campus Cruisade for Christ at NJIT' },
{ value: 'Caribbean Student Organization', label: 'Caribbean Student Organization' },
{ value: 'Collegiate Association for the Research of Principles', label: 'Collegiate Association for the Research of Principles' },
{ value: 'Computation and Communication Club', label: 'Computation and Communication Club' },
{ value: 'Coptic Society', label: 'Coptic Society' },
{ value: 'DeepCS (Grad. CS Club)', label: 'DeepCS (Grad. CS Club)' },
{ value: 'Delta Epsilon Iota (Honor Society)', label: 'Delta Epsilon Iota (Honor Society)' },
{ value: 'Delta Epsilon Psi Fraternity', label: 'Delta Epsilon Psi Fraternity' },
{ value: 'Delta Phi Epsilon Sorority', label: 'Delta Phi Epsilon Sorority' },
{ value: 'Diversity Programs/Campus Center', label: 'Diversity Programs/Campus Center' },
{ value: 'Eta Kappa Nu', label: 'Eta Kappa Nu' },
{ value: 'Electrical and Computer Engineering Club', label: 'Electrical and Computer Engineering Club' },
{ value: 'Engineers Without Borders', label: 'Engineers Without Borders' },
{ value: 'Fencing', label: 'Fencing' },
{ value: 'Filipino Student Association', label: 'Filipino Student Association' },
{ value: 'FSAE', label: 'FSAE' },
{ value: 'Filmmaking Club', label: 'Filmmaking Club' },
{ value: 'Golf Club', label: 'Golf Club' },
{ value: 'Graduate Biomedical Engineering Society', label: 'Graduate Biomedical Engineering Society' },
{ value: 'Graduate Student Association', label: 'Graduate Student Association' },
{ value: 'Habitat for Humanity', label: 'Habitat for Humanity' },
{ value: 'Hellenic Cultural Association', label: 'Hellenic Cultural Association' },
{ value: 'HERO Campaign', label: 'HERO Campaign' },
{ value: 'Highlander Chess Club', label: 'Highlander Chess Club' },
{ value: 'Highlander League of Legends Club', label: 'Highlander League of Legends Club' },
{ value: 'Highlander Soccer Club', label: 'Highlander Soccer Club' },
{ value: 'HighlanderThon', label: 'HighlanderThon' },
{ value: 'HOSA', label: 'HOSA' },
{ value: 'Honors Student Council', label: 'Honors Student Council' },
{ value: 'Improv Technicians', label: 'Improv Technicians' },
{ value: 'Industrial Design Society of America', label: 'Industrial Design Society of America' },
{ value: 'Information Systems', label: 'Information Systems' },
{ value: 'Innovation Acceleration Club', label: 'Innovation Acceleration Club' },
{ value: 'Institute of Electrical and Electronics Engineers', label: 'Institute of Electrical and Electronics Engineers' },
{ value: 'International Concrete Repair Institute', label: 'International Concrete Repair Institute' },
{ value: 'Institute of Industrial Engineers', label: 'Institute of Industrial Engineers' },
{ value: 'Inter Fraternity Council', label: 'Inter Fraternity Council' },
{ value: 'Inter Fraternity Sorority Council', label: 'Inter Fraternity Sorority Council' },
{ value: 'InterVarsity Christian Fellowship', label: 'InterVarsity Christian Fellowship' },
{ value: 'Iota Phi Theta Fraternity', label: 'Iota Phi Theta Fraternity' },
{ value: 'Kappa Xi Kappa (Fraternity)', label: 'Kappa Xi Kappa (Fraternity)' },
{ value: 'Korea Campus Crusade for Christ', label: 'Korea Campus Crusade for Christ' },
{ value: 'Lambda Sigma Upsilon Latino Fraternity, Inc.', label: 'Lambda Sigma Upsilon Latino Fraternity, Inc.' },
{ value: 'Lambda Tau Omega (Sorority)', label: 'Lambda Tau Omega (Sorority)' },
{ value: 'Lambda Theta Phi (Fraternity)', label: 'Lambda Theta Phi (Fraternity)' },
{ value: 'Lambda Upsilon Lambda Fraternity Inc.', label: 'Lambda Upsilon Lambda Fraternity Inc.' },
{ value: 'Latin American Student Organization', label: 'Latin American Student Organization' },
{ value: 'Math Graduates', label: 'Math Graduates' },
{ value: 'Mathematical Sciences Group', label: 'Mathematical Sciences Group' },
{ value: 'Men’s Baseball', label: 'Men’s Baseball' },
{ value: 'Men’s Basketball', label: 'Men’s Basketball' },
{ value: 'Men’s Cross Country', label: 'Men’s Cross Country' },
{ value: 'Men’s Lacrosse', label: 'Men’s Lacrosse' },
{ value: 'Men’s Soccer', label: 'Men’s Soccer' },
{ value: 'Men’s Swimming and Diving', label: 'Men’s Swimming and Diving' },
{ value: 'Men’s Tennis', label: 'Men’s Tennis' },
{ value: 'Men’s Track and Field (Indoor)', label: 'Men’s Track and Field (Indoor)' },
{ value: 'Men’s Track and Field (Outdoor)', label: 'Men’s Track and Field (Outdoor)' },
{ value: 'Men’s Volleyball', label: 'Men’s Volleyball' },
{ value: 'Multicultural Greek Council', label: 'Multicultural Greek Council' },
{ value: 'Muslim Student Association', label: 'Muslim Student Association' },
{ value: 'National Society of Professional Engineers NJIT Student Chapter', label: 'National Society of Professional Engineers NJIT Student Chapter' },
{ value: 'National Residence Hall Honorary', label: 'National Residence Hall Honorary' },
{ value: 'National Society of Black Engineers', label: 'National Society of Black Engineers' },
{ value: 'National Society of Collegiate Scholars', label: 'National Society of Collegiate Scholars' },
{ value: 'Newman Club', label: 'Newman Club' },
{ value: 'NJIT Accounting Club', label: 'NJIT Accounting Club' },
{ value: 'NJIT Amnesty International', label: 'NJIT Amnesty International' },
{ value: 'NJIT Amateur Radio Club', label: 'NJIT Amateur Radio Club' },
{ value: 'NJIT Anime Club', label: 'NJIT Anime Club' },
{ value: 'NJIT Billiards Club', label: 'NJIT Billiards Club' },
{ value: 'NJIT Game Club', label: 'NJIT Game Club' },
{ value: 'NJIT Mentor Network', label: 'NJIT Mentor Network' },
{ value: 'NJIT Pilanders', label: 'NJIT Pilanders' },
{ value: 'NJIT Rugby', label: 'NJIT Rugby' },
{ value: 'NJIT Robotics Club', label: 'NJIT Robotics Club' },
{ value: 'NJIT SIGGRAPH', label: 'NJIT SIGGRAPH' },
{ value: 'None', label: 'None'},
{ value: 'Nucleus Yearbook', label: 'Nucleus Yearbook' },
{ value: 'Omicron Delta Kappa National Leadership Honor Society', label: 'Omicron Delta Kappa National Leadership Honor Society' },
{ value: 'Order of Omega', label: 'Order of Omega' },
{ value: 'Persian Society', label: 'Persian Society' },
{ value: 'Ph.D Club', label: 'Ph.D Club' },
{ value: 'Phi Beta Sigma Fraternity', label: 'Phi Beta Sigma Fraternity' },
{ value: 'Phi Delta Epsilon', label: 'Phi Delta Epsilon' },
{ value: 'Phi Eta Sigma', label: 'Phi Eta Sigma' },
{ value: 'Phi Sigma Kappa Fraternity', label: 'Phi Sigma Kappa Fraternity' },
{ value: 'Photography Club', label: 'Photography Club' },
{ value: 'Pi Kappa Phi Fraternity', label: 'Pi Kappa Phi Fraternity' },
{ value: 'Pi Tau Sigma', label: 'Pi Tau Sigma' },
{ value: 'Pre Health Society', label: 'Pre Health Society' },
{ value: 'Pre-Dental Society', label: 'Pre-Dental Society' },
{ value: 'Pre-Law Society', label: 'Pre-Law Society' },
{ value: 'Project Dental All', label: 'Project Dental All' },
{ value: 'Psi Upsilon Fraternity', label: 'Psi Upsilon Fraternity' },
{ value: 'Residence Hall Association', label: 'Residence Hall Association' },
{ value: 'Rotaract Club of NJIT', label: 'Rotaract Club of NJIT' },
{ value: 'Sanskar', label: 'Sanskar' },
{ value: 'Saudi Students Club', label: 'Saudi Students Club' },
{ value: 'Students Society of Contractors', label: 'Students Society of Contractors' },
{ value: 'Science and Engineering Innovation Lab', label: 'Science and Engineering Innovation Lab' },
{ value: 'School of Management Graduate Business Club', label: 'School of Management Graduate Business Club' },
{ value: 'Sigma Alpha Epsilon', label: 'Sigma Alpha Epsilon' },
{ value: 'Sigma Pi Fraternity', label: 'Sigma Pi Fraternity' },
{ value: 'Sigma Beta Rho', label: 'Sigma Beta Rho' },
{ value: 'Sigma Psi Kappa Sorority', label: 'Sigma Psi Kappa Sorority' },
{ value: 'Society of Commuting Students', label: 'Society of Commuting Students' },
{ value: 'Society of Hispanic Professional Engineers', label: 'Society of Hispanic Professional Engineers' },
{ value: 'Society of Musical Arts', label: 'Society of Musical Arts' },
{ value: 'Society of Physics Students', label: 'Society of Physics Students' },
{ value: 'Society of Women Engineers', label: 'Society of Women Engineers' },
{ value: 'Speaking Club', label: 'Speaking Club' },
{ value: 'Students For Life of America', label: 'Students For Life of America' },
{ value: 'Tau Delta Phi Fraternity', label: 'Tau Delta Phi Fraternity' },
{ value: 'Tau Kappa Epsilon Fraternity', label: 'Tau Kappa Epsilon Fraternity' },
{ value: 'The Vector Newspaper', label: 'The Vector Newspaper' },
{ value: 'Theta Chi Fraternity', label: 'Theta Chi Fraternity' },
{ value: 'Transportation Club', label: 'Transportation Club' },
{ value: 'Toastmasters International', label: 'Toastmasters International' },
{ value: 'Veterans Students Organization', label: 'Veterans Students Organization' },
{ value: 'Women in Computing Society', label: 'Women in Computing Society' },
{ value: 'Women’s Basketball', label: 'Women’s Basketball' },
{ value: 'Women’s Cross Country', label: 'Women’s Cross Country' },
{ value: 'Women’s Soccer', label: 'Women’s Soccer' },
{ value: 'Women’s Tennis', label: 'Women’s Tennis' },
{ value: 'Women’s Track and Field (Indoor)', label: 'Women’s Track and Field (Indoor)' },
{ value: 'Women’s Track and Field (Outdoor)', label: 'Women’s Track and Field (Outdoor)' },
{ value: 'Women’s Volleyball', label: 'Women’s Volleyball' },
{ value: 'WJTB Radio', label: 'WJTB Radio' }]
