export const pageTypes = {
  TAGS_QUESTIONS : "TAGS_QUESTIONS",
  SORT_CONTACTS : "SORT_CONTACTS",
  GROUP_CONTACTS : "GROUP_CONTACTS",
  BUCKET_QUESTIONS: "BUCKET_QUESTIONS",
  SELECT_CONTACTS : "SELECT_CONTACTS",
}
